/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as NewcomersRouteImport } from './routes/newcomers'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlgorithmRouteImport } from './routes/algorithm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const NewcomersRoute = NewcomersRouteImport.update({
  id: '/newcomers',
  path: '/newcomers',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmRoute = AlgorithmRouteImport.update({
  id: '/algorithm',
  path: '/algorithm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algorithm': typeof AlgorithmRoute
  '/analytics': typeof AnalyticsRoute
  '/newcomers': typeof NewcomersRoute
  '/simulation': typeof SimulationRoute
  '/topics': typeof TopicsRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algorithm': typeof AlgorithmRoute
  '/analytics': typeof AnalyticsRoute
  '/newcomers': typeof NewcomersRoute
  '/simulation': typeof SimulationRoute
  '/topics': typeof TopicsRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/algorithm': typeof AlgorithmRoute
  '/analytics': typeof AnalyticsRoute
  '/newcomers': typeof NewcomersRoute
  '/simulation': typeof SimulationRoute
  '/topics': typeof TopicsRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/algorithm'
    | '/analytics'
    | '/newcomers'
    | '/simulation'
    | '/topics'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/algorithm'
    | '/analytics'
    | '/newcomers'
    | '/simulation'
    | '/topics'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/algorithm'
    | '/analytics'
    | '/newcomers'
    | '/simulation'
    | '/topics'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlgorithmRoute: typeof AlgorithmRoute
  AnalyticsRoute: typeof AnalyticsRoute
  NewcomersRoute: typeof NewcomersRoute
  SimulationRoute: typeof SimulationRoute
  TopicsRoute: typeof TopicsRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newcomers': {
      id: '/newcomers'
      path: '/newcomers'
      fullPath: '/newcomers'
      preLoaderRoute: typeof NewcomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithm': {
      id: '/algorithm'
      path: '/algorithm'
      fullPath: '/algorithm'
      preLoaderRoute: typeof AlgorithmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlgorithmRoute: AlgorithmRoute,
  AnalyticsRoute: AnalyticsRoute,
  NewcomersRoute: NewcomersRoute,
  SimulationRoute: SimulationRoute,
  TopicsRoute: TopicsRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
